# gpu设置
device: "cuda"

# 模型选择
method:
  # 生成雾方法，可选: None, MiDaS_Deep
  haze: "MiDaS_Deep"

  # 去雾方法，可选: None, DIP, DENET, FALCON
  dehaze: "FALCON"

  # 检测器，可选: YOLOV3, DE_NET, DITOL
  detector: "DITOL"

  # 跟踪算法，可选: SORT
  tracker: "SORT"

#模型是否启用检测器
detector_flag: True

#模型是否启用追踪器
tracker_flag: True

# 检测与跟踪参数
confidence_threshold: 0.4
iou_threshold: 0.5

# 数据集路径与设置
dataset:
  fog_strength: 0.75
  train_ratio: 0.8
  val_ratio: 0.1
  batch: 16
  is_mask: True
  path: "./data/UAV-M"
  data_path: "UAV-benchmark-M"
  label_path: "UAV-benchmark-MOTD_v1.0/GT"
  is_clean: True
  shuffle: True

# 是否保存可视化结果
save_output: true

# 随机种子
seed: 2025

# 训练参数
train:
  debug: False

  # epochs
  epochs: 80

  # 是否恢复训练
  resume_training: False

  # 学习率设置
  lr: 0.001

  # 是否冻结去雾模型
  freeze_dehaze: False

  # 是否在模型中先训练去雾模型，后训练检测器
  pretrain_flag: True

  # 去雾模型先训练epoch
  dehaze_epoch: 5

