# gpu设置
device: "cuda"

experiment_name: "exp1_dcp_yolov5_sort"

# 生成雾方法，可选: None,MiDaS_Deep
haze_method: "MiDaS_Deep"

# 检测器，可选: IA_YOLOV3
detector: "IA_YOLOV3"

# 跟踪算法，可选: SORT
tracker: "SORT"

# 检测与跟踪参数
confidence_threshold: 0.4
iou_threshold: 0.5

# 数据集路径与设置
dataset:
  path: "./data/UAV-M"
  data_path: "UAV-benchmark-M"
  label_path: "UAV-benchmark-MOTD_v1.0/GT"

# 是否保存可视化结果
save_output: true

# 随机种子
seed: 2025

# 是否用到干净数据集
is_clean: True

# 训练参数
train:
  # 每log_interval次就print一次loss
  log_interval: 10

  # 每checkpoint_save_interval次就存储一次检查点
  checkpoint_save_interval: 5

  # epochs
  epochs: 1

  # 是否从 checkpoint 恢复训练
  resume_training: false

  # 学习率设置
  lr: 0.001

