device: cuda
detector_flag: true
tracker_flag: true
method:
  haze: MiDaS_Deep
  dehaze: NONE
  detector: IA_YOLOV3
  tracker: tracker
  track_method: bytetrack
conf_threshold: 0.4
iou_threshold: 0.5
dataset:
  fog_strength: 0.5
  train_ratio: 0.8
  val_ratio: 0.1
  batch: 12
  is_mask: true
  path: ./data/UAV-M
  data_path: UAV-benchmark-M
  label_path: UAV-benchmark-MOTD_v1.0/GT
  is_clean: false
  shuffle: true
  nums_worker: 16
save_output: true
seed: 2025
train:
  checkpoint_interval: 5
  log_interval: 10
  debug: false
  epochs: 80
  resume_training: false
  lr: 0.001
  freeze_dehaze: false
  pretrain_flag: false
  dehaze_epoch: 5
